baseurl: "/pages"

collections:
  home:
    output: true
    permalink: /home/:title/
  nieuwsbrief:
    output: true
    permalink: /nieuwsbrief/:title/
  dynamic:
    output: true
    permalink: /dynamic/:title/
    paginate: 5
    paginate_path: "/dynamic/page:num/"
    